version: '3'
services:
  web:
    container_name: employment-frontend
    restart: always
    build: employment/.
    ports:
      - '3000:80'
    links:
      - server
  server:
    container_name: employment-server
    restart: always
    build: employment-server/.
    ports:
      - '80:4000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'